CREATE TABLE app_config(
    id SERIAL NOT NULL,
    app_name text NOT NULL,
    logo text NOT NULL,
    smtp_host text,
    smtp_port text,
    smtp_email text,
    smtp_password text,
    smtp_from_email text,
    smtp_domain text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE a_class(
    id SERIAL NOT NULL,
    homebase integer,
    grade integer,
    major integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT a_class_grade_fkey FOREIGN key(grade) REFERENCES a_grade(id)
);

-- Generated by the database client.
CREATE TABLE a_grade(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT a_grade_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);
CREATE TABLE a_graduation (
    id SERIAL PRIMARY KEY,
    userid INTEGER REFERENCES u_students(id) ON DELETE CASCADE,
    agency VARCHAR(255),
    description TEXT,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);
-- Generated by the database client.
CREATE TABLE a_homebase(
    id SERIAL NOT NULL,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE a_major(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE a_periode(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    isactive boolean DEFAULT false,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT a_periode_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);

-- Generated by the database client.
CREATE TABLE a_subject(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    cover text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE at_class(
    id SERIAL NOT NULL,
    teacher_id integer NOT NULL,
    class_id integer NOT NULL,
    subject_id integer NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT at_class_class_id_fkey FOREIGN key(class_id) REFERENCES a_class(id)
);


-- Generated by the database client.
CREATE TABLE at_subject(
    id SERIAL NOT NULL,
    teacher integer NOT NULL,
    subject integer NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT at_subject_subject_fkey FOREIGN key(subject) REFERENCES a_subject(id),
    CONSTRAINT at_subject_teacher_fkey FOREIGN key(teacher) REFERENCES u_teachers(id)
);


-- Generated by the database client.
CREATE TABLE c_answer(
    id SERIAL NOT NULL,
    exam integer,
    student integer,
    question integer,
    mc text,
    essay text,
    correct text,
    point integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT c_answer_student_fkey FOREIGN key(student) REFERENCES u_students(id),
    CONSTRAINT c_answer_question_fkey FOREIGN key(question) REFERENCES c_question(id)
);


-- Generated by the database client.
CREATE TABLE c_bank(
    id SERIAL NOT NULL,
    homebase integer,
    teacher integer,
    subject integer,
    btype text NOT NULL,
    name varchar(255) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT c_bank_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id),
    CONSTRAINT c_bank_subject_fkey FOREIGN key(subject) REFERENCES a_subject(id),
    CONSTRAINT c_bank_teacher_fkey FOREIGN key(teacher) REFERENCES u_teachers(id)
);


-- Generated by the database client.
CREATE TABLE c_class(
    id SERIAL NOT NULL,
    exam integer,
    classid integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT c_class_classid_fkey FOREIGN key(classid) REFERENCES a_class(id)
);

-- Generated by the database client.
CREATE TABLE c_ebank(
    id SERIAL NOT NULL,
    exam integer,
    bank integer,
    pg integer,
    essay integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT c_ebank_bank_fkey FOREIGN key(bank) REFERENCES c_bank(id)
);


-- Generated by the database client.
CREATE TABLE c_exam(
    id SERIAL NOT NULL,
    homebase integer,
    teacher integer,
    name varchar(255) NOT NULL,
    duration integer NOT NULL,
    isactive boolean DEFAULT true,
    isshuffle boolean DEFAULT false,
    mc_score integer NOT NULL,
    essay_score integer NOT NULL,
    token text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT c_exam_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id),
    CONSTRAINT c_exam_teacher_fkey FOREIGN key(teacher) REFERENCES u_teachers(id)
);


-- Generated by the database client.
CREATE TABLE c_question(
    id SERIAL NOT NULL,
    bank integer,
    qtype integer NOT NULL,
    question text NOT NULL,
    a text,
    b text,
    c text,
    d text,
    e text,
    qkey text,
    poin integer DEFAULT 0,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT c_question_bank_fkey FOREIGN key(bank) REFERENCES c_bank(id)
);


-- Generated by the database client.
CREATE TABLE cl_students(
    id SERIAL NOT NULL,
    homebase integer,
    periode integer,
    classid integer,
    student integer,
    student_name varchar(255) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT cl_students_classid_fkey FOREIGN key(classid) REFERENCES a_class(id),
    CONSTRAINT cl_students_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id),
    CONSTRAINT cl_students_periode_fkey FOREIGN key(periode) REFERENCES a_periode(id),
    CONSTRAINT cl_students_student_fkey FOREIGN key(student) REFERENCES u_students(id)
);


-- Generated by the database client.
CREATE TABLE l_cclass(
    id SERIAL NOT NULL,
    chapter integer,
    classid integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT l_cclass_classid_fkey FOREIGN key(classid) REFERENCES a_class(id)
);


-- Generated by the database client.
CREATE TABLE l_chapter(
    id SERIAL NOT NULL,
    subject integer,
    teacher integer,
    title text NOT NULL,
    target text NOT NULL,
    order_number integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT l_chapter_subject_fkey FOREIGN key(subject) REFERENCES a_subject(id),
    CONSTRAINT l_chapter_teacher_fkey FOREIGN key(teacher) REFERENCES u_teachers(id)
);


-- Generated by the database client.
CREATE TABLE l_content(
    id SERIAL NOT NULL,
    chapter integer,
    title text NOT NULL,
    target text NOT NULL,
    order_number integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT l_content_chapter_fkey FOREIGN key(chapter) REFERENCES l_chapter(id)
);


-- Generated by the database client.
CREATE TABLE l_file(
    id SERIAL NOT NULL,
    content integer,
    title text NOT NULL,
    file text,
    video text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE logs(
    id SERIAL NOT NULL,
    student integer,
    teacher integer,
    admin integer,
    exam integer,
    ip text,
    browser text,
    islogin boolean,
    ispenalty boolean,
    isactive boolean,
    isdone boolean,
    "action" text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT logs_student_fkey FOREIGN key(student) REFERENCES u_students(id),
    CONSTRAINT logs_teacher_fkey FOREIGN key(teacher) REFERENCES u_teachers(id),
    CONSTRAINT logs_admin_fkey FOREIGN key(admin) REFERENCES u_admin(id)
);


-- Generated by the database client.
CREATE TABLE t_categories(
    id SERIAL NOT NULL,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE t_examiner(
    id SERIAL NOT NULL,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE t_indicators(
    id SERIAL NOT NULL,
    name text NOT NULL,
    category_id integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT t_indicators_category_id_fkey FOREIGN key(category_id) REFERENCES t_categories(id)
);


-- Generated by the database client.
CREATE TABLE t_juz(
    id SERIAL NOT NULL,
    name varchar(100) NOT NULL,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE t_juzitems(
    id SERIAL NOT NULL,
    juz_id integer,
    surah_id integer,
    from_ayat numeric,
    to_ayat numeric,
    lines numeric,
    PRIMARY KEY(id),
    CONSTRAINT t_juzitems_juz_id_fkey FOREIGN key(juz_id) REFERENCES t_juz(id),
    CONSTRAINT t_juzitems_surah_id_fkey FOREIGN key(surah_id) REFERENCES t_surah(id)
);


-- Generated by the database client.
CREATE TABLE t_process(
    id SERIAL NOT NULL,
    userid integer,
    periode_id integer,
    type_id integer,
    juz_id integer,
    surah_id integer,
    from_count integer,
    to_count integer,
    from_line integer,
    to_line integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT t_process_userid_fkey FOREIGN key(userid) REFERENCES u_students(id),
    CONSTRAINT t_process_periode_id_fkey FOREIGN key(periode_id) REFERENCES a_periode(id),
    CONSTRAINT t_process_type_id_fkey FOREIGN key(type_id) REFERENCES t_type(id),
    CONSTRAINT t_process_juz_id_fkey FOREIGN key(juz_id) REFERENCES t_juz(id),
    CONSTRAINT t_process_surah_id_fkey FOREIGN key(surah_id) REFERENCES t_surah(id)
);


-- Generated by the database client.
CREATE TABLE t_scoring(
    id SERIAL NOT NULL,
    userid integer,
    periode_id integer,
    examiner_id integer,
    type_id integer,
    category_id integer,
    indicator_id integer,
    poin text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT t_scoring_userid_fkey FOREIGN key(userid) REFERENCES u_students(id),
    CONSTRAINT t_scoring_periode_id_fkey FOREIGN key(periode_id) REFERENCES a_periode(id),
    CONSTRAINT t_scoring_examiner_id_fkey FOREIGN key(examiner_id) REFERENCES t_examiner(id),
    CONSTRAINT t_scoring_type_id_fkey FOREIGN key(type_id) REFERENCES t_type(id),
    CONSTRAINT t_scoring_category_id_fkey FOREIGN key(category_id) REFERENCES t_categories(id),
    CONSTRAINT t_scoring_indicator_id_fkey FOREIGN key(indicator_id) REFERENCES t_indicators(id)
);



-- Generated by the database client.
CREATE TABLE t_surah(
    id SERIAL NOT NULL,
    name varchar(100) NOT NULL,
    ayat integer NOT NULL,
    lines integer,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE t_target(
    id SERIAL NOT NULL,
    grade_id integer,
    juz_id integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT t_target_grade_id_fkey FOREIGN key(grade_id) REFERENCES a_grade(id),
    CONSTRAINT t_target_juz_id_fkey FOREIGN key(juz_id) REFERENCES t_juz(id)
);



-- Generated by the database client.
CREATE TABLE t_type(
    id SERIAL NOT NULL,
    name varchar(100) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE u_admin(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    password text NOT NULL,
    level text DEFAULT 'admin'::text,
    activation text,
    isactive boolean DEFAULT false,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT u_admin_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);



-- Generated by the database client.
CREATE TABLE u_parents(
    id SERIAL NOT NULL,
    student integer,
    email text NOT NULL,
    username text NOT NULL,
    phone text NOT NULL,
    password text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX u_parents_email_key ON public.u_parents USING btree (email);
CREATE UNIQUE INDEX u_parents_phone_key ON public.u_parents USING btree (phone);


-- Generated by the database client.
CREATE TABLE u_students(
    id SERIAL NOT NULL,
    homebase integer,
    entry integer,
    name text NOT NULL,
    nis text,
    password text,
    level text DEFAULT 'student'::text,
    gender varchar(255),
    isactive boolean DEFAULT true,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT u_students_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);



-- Generated by the database client.
CREATE TABLE u_teachers(
    id SERIAL NOT NULL,
    username text NOT NULL,
    name text NOT NULL,
    email text,
    img text,
    homebase integer NOT NULL,
    homeroom boolean DEFAULT false,
    class integer,
    phone text,
    password text NOT NULL,
    gender varchar(10) NOT NULL,
    level text DEFAULT 'teacher'::text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT u_teachers_class_fkey FOREIGN key(class) REFERENCES a_class(id),
    CONSTRAINT u_teachers_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);


-- DATABSE
-- Generated by the database client.
-- Generated by the database client.
CREATE TABLE db_province(
    id character(2) NOT NULL,
    name varchar(255) NOT NULL,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE db_city(
    id character(4) NOT NULL,
    provinceid character(2) NOT NULL,
    name varchar(255) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT wil_regional_provinsi_id_fkey FOREIGN key(provinceid) REFERENCES db_province(id)
);
CREATE INDEX regional_provinsi_id_index ON public.db_city USING btree (provinceid);


-- Generated by the database client.
CREATE TABLE db_district(
    id character(7) NOT NULL,
    cityid character(4) NOT NULL,
    name varchar(255) NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT wil_kecamatan_regional_id_fkey FOREIGN key(cityid) REFERENCES db_city(id)
);
CREATE INDEX kecamatan_id_index ON public.db_district USING btree (cityid);

-- Generated by the database client.
CREATE TABLE db_village(
    id character(20) NOT NULL,
    districtid character(20),
    name varchar(255),
    PRIMARY KEY(id),
    CONSTRAINT wil_desa_kecamatan_id_fkey FOREIGN key(districtid) REFERENCES db_district(id)
);
CREATE INDEX desa_kecamatan_id_index ON public.db_village USING btree (districtid);



CREATE TABLE db_student(
    id SERIAL NOT NULL,
    userid INT REFERENCES u_students(id) ON DELETE CASCADE,
    homebaseid INT REFERENCES a_homebase(id) ON DELETE CASCADE,
    homebase_name VARCHAR(255),
    entryid INT REFERENCES a_periode(id) ON DELETE CASCADE,
    entry_name VARCHAR(255),
    nis TEXT,
    nisn TEXT,
    name TEXT,
    gender VARCHAR(255),
    birth_place TEXT,
    birth_date DATE,
    height TEXT,
    weight TEXT,
    head TEXT,
    order_number TEXT,
    siblings TEXT,
    provinceid character(2),
    province_name TEXT,
    cityid character(4),
    city_name TEXT,
    districtid character(7),
    district_name TEXT,
    villageid character(20),
    village_name TEXT,
    postal_code TEXT,
    address TEXT,
    father_nik varchar(50),
    father_name varchar(255),
    father_birth_place varchar(255),
    father_birth_date date,
    father_job TEXT,
    father_phone TEXT,
    mother_nik varchar(50),
    mother_name varchar(255),
    mother_birth_place varchar(255),
    mother_birth_date date,
    mother_job TEXT,
    mother_phone TEXT,
    PRIMARY KEY(id)
);

CREATE TABLE db_family(
    id SERIAL PRIMARY KEY NOT NULL,
    userid INT REFERENCES u_students(id) ON DELETE CASCADE,
    name TEXT,
    gender TEXT,
    birth_date DATE
);


-- Berikan penjelasan table relasi disini

-- Update foreign key constraints for geographical tables
ALTER TABLE db_city 
    DROP CONSTRAINT IF EXISTS wil_regional_provinsi_id_fkey,
    ADD CONSTRAINT fk_city_province 
    FOREIGN KEY (provinceid) 
    REFERENCES db_province(id) 
    ON DELETE CASCADE;

ALTER TABLE db_district 
    DROP CONSTRAINT IF EXISTS wil_kecamatan_regional_id_fkey,
    ADD CONSTRAINT fk_district_city 
    FOREIGN KEY (cityid) 
    REFERENCES db_city(id) 
    ON DELETE CASCADE;

ALTER TABLE db_village 
    DROP CONSTRAINT IF EXISTS wil_desa_kecamatan_id_fkey,
    ADD CONSTRAINT fk_village_district 
    FOREIGN KEY (districtid) 
    REFERENCES db_district(id) 
    ON DELETE CASCADE;

-- Update indexes for better performance
DROP INDEX IF EXISTS regional_provinsi_id_index;
CREATE INDEX idx_city_province ON db_city(provinceid);

DROP INDEX IF EXISTS kecamatan_id_index;
CREATE INDEX idx_district_city ON db_district(cityid);

DROP INDEX IF EXISTS desa_kecamatan_id_index;
CREATE INDEX idx_village_district ON db_village(districtid);


ALTER TABLE "db_student" ADD COLUMN "createdat" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "u_students" ADD COLUMN "periode" INT REFERENCES a_periode(id) ON DELETE CASCADE;

SELECT setval('db_student_id_seq', (SELECT MAX(id) FROM db_student));


-- CMS
CREATE TABLE cms_home(
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT,
    tagline TEXT,
    description TEXT,
    video_url TEXT,
    youtube TEXT,
    instagram TEXT,
    facebook TEXT,
    ppdb_url TEXT,
    logo TEXT,
    address TEXT,
    title_reason TEXT,
    desc_reason TEXT,
    title_facility TEXT,
    desc_facility TEXT,
    primary_color TEXT,
    secondary_color TEXT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)



CREATE TABLE cms_reason(
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT,
    image TEXT,
    description TEXT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE cms_facility(
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT,
    image TEXT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE cms_testimoni(
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT,
    description TEXT,
    testimonial TEXT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)


CREATE TABLE cms_category(
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE cms_news(
    id SERIAL PRIMARY KEY NOT NULL,
    category_id INT REFERENCES cms_category(id) ON DELETE CASCADE,
    title TEXT,
    image TEXT,
    content TEXT,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE cms_visitors (
    id SERIAL PRIMARY KEY NOT NULL,
    ip_address TEXT NOT NULL,
    country TEXT,
    page_type TEXT NOT NULL,
    content_id INTEGER,
    visit_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_visitors_ip_date ON cms_visitors(ip_address, visit_date);
CREATE INDEX idx_visitors_page_type ON cms_visitors(page_type);
