CREATE TABLE a_branch(
    id SERIAL NOT NULL,
    name text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    homebase integer,
    PRIMARY KEY(id),
    CONSTRAINT a_branch_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);

-- Generated by the database client.
CREATE TABLE a_category(
    id SERIAL NOT NULL,
    name text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    homebase integer,
    PRIMARY KEY(id),
    CONSTRAINT a_category_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);

-- Generated by the database client.
CREATE TABLE a_class(
    id SERIAL NOT NULL,
    homebase integer,
    grade integer,
    major integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT a_class_grade_fkey FOREIGN key(grade) REFERENCES a_grade(id)
);

-- Generated by the database client.
CREATE TABLE a_grade(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT a_grade_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);

CREATE TABLE a_homebase(
    id SERIAL NOT NULL,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

-- Generated by the database client.
CREATE TABLE a_major(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);


-- Generated by the database client.
CREATE TABLE a_periode(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    isactive boolean DEFAULT false,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT a_periode_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);

-- Generated by the database client.
CREATE TABLE a_subject(
    id SERIAL NOT NULL,
    homebase integer,
    name text NOT NULL,
    cover text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    categoryid integer,
    branchid integer,
    presensi integer,
    attitude integer,
    daily integer,
    final integer
);

-- Generated by the database client.
CREATE TABLE at_subject(
    id SERIAL NOT NULL,
    teacher integer NOT NULL,
    subject integer NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT at_subject_subject_fkey FOREIGN key(subject) REFERENCES a_subject(id),
    CONSTRAINT at_subject_teacher_fkey FOREIGN key(teacher) REFERENCES u_teachers(id)
);

CREATE TABLE cl_students(
    id SERIAL NOT NULL,
    homebase integer,
    periode integer,
    classid integer,
    student integer,
    student_name varchar(255) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT cl_students_classid_fkey FOREIGN key(classid) REFERENCES a_class(id),
    CONSTRAINT cl_students_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id),
    CONSTRAINT cl_students_periode_fkey FOREIGN key(periode) REFERENCES a_periode(id),
    CONSTRAINT cl_students_student_fkey FOREIGN key(student) REFERENCES u_students(id)
);


-- Generated by the database client.
CREATE TABLE c_answer(
    id SERIAL NOT NULL,
    exam integer,
    student integer,
    question integer,
    mc text,
    essay text,
    correct text,
    point integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE c_bank(
    id SERIAL NOT NULL,
    homebase integer,
    teacher integer,
    subject integer,
    btype text NOT NULL,
    name varchar(255) NOT NULL,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE c_class(
    id SERIAL NOT NULL,
    exam integer,
    classid integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE c_ebank(
    id SERIAL NOT NULL,
    exam integer,
    bank integer,
    pg integer,
    essay integer,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE c_exam(
    id SERIAL NOT NULL,
    homebase integer,
    teacher integer,
    name varchar(255) NOT NULL,
    duration integer NOT NULL,
    isactive boolean DEFAULT true,
    isshuffle boolean DEFAULT false,
    mc_score integer NOT NULL,
    essay_score integer NOT NULL,
    token text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- Generated by the database client.
CREATE TABLE c_question(
    id SERIAL NOT NULL,
    bank integer,
    qtype integer NOT NULL,
    question text NOT NULL,
    a text,
    b text,
    c text,
    d text,
    e text,
    qkey text,
    poin integer DEFAULT 0,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


-- Generated by the database client.
CREATE TABLE u_students(
    id SERIAL NOT NULL,
    homebase integer,
    entry integer,
    name text NOT NULL,
    nis text,
    password text,
    level text DEFAULT 'student'::text,
    gender varchar(255),
    isactive boolean DEFAULT true,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    periode integer,
    PRIMARY KEY(id),
    CONSTRAINT u_students_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id),
    CONSTRAINT u_students_periode_fkey FOREIGN key(periode) REFERENCES a_periode(id)
);

-- Generated by the database client.
CREATE TABLE u_teachers(
    id SERIAL NOT NULL,
    username text NOT NULL,
    name text NOT NULL,
    email text,
    img text,
    homebase integer NOT NULL,
    homeroom boolean DEFAULT false,
    class integer,
    phone text,
    password text NOT NULL,
    gender varchar(10) NOT NULL,
    level text DEFAULT 'teacher'::text,
    createdat timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    CONSTRAINT u_teachers_class_fkey FOREIGN key(class) REFERENCES a_class(id),
    CONSTRAINT u_teachers_homebase_fkey FOREIGN key(homebase) REFERENCES a_homebase(id)
);
